---
title: "Jaccard index"
author: "Enrico Gaffo"
date: "`r Sys.Date()`"
output: 
  html_document: 
    toc: yes
    toc_float: yes
    code_folding: hide
params:
  output_dir: "DM1_jaccard"
  sumBench_perf_metrics_qs: "DM1_ev"
  sice: FALSE
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
library(data.table)
```

# Jaccard

```{r}
## Jaccard similarity function
## https://www.r-bloggers.com/2021/11/how-to-calculate-jaccard-similarity-in-r/
jaccard <- function(a, b) {
    if(length(a) == 0 & length(b) == 0){
        return(1)
    }else{
        intersection <- length(intersect(a, b))
        if(is.null(intersection)){
            return(0)
        }else{
            union <- length(a) + length(b) - intersection
            return(intersection / union)
        }
    }
}
```

```{r}
ds_names <- c("DM1", "IPF", "MS", "IDC") 

input_dirs <- paste0(ds_names, "_evaluations")

padj <- rbindlist(lapply(setNames(file.path(input_dirs, "adj_pval_deind.csv.gz"), #"pval_deind.csv.gz"
                                  nm = ds_names), 
               fread), 
               idcol = "DS")

padj <- padj[MZP == "bulk" & DsType == "de"]
```

```{r}
padj[, Gid := seq_along(preds), by = .(DS, Dataset, Method)]

padj_l <- split(padj, drop = F, by = c("DS", "Dataset"), flatten = F)

jaccard_dists <- 
    rbindlist(lapply(padj_l, function(dataset){
        
        rbindlist(lapply(dataset, function(simds){
            
            mt <- as.matrix(data.frame(dcast(simds[, .(Method, preds, Gid)], 
                                             Gid ~ Method, 
                                             value.var = "preds", 
                                             fill = 0), 
                                       row.names = "Gid"))
            as.data.table(as.matrix(dist(x = t(mt) <= .1, method = "binary")),
                          keep.rownames = "Method")
        }), 
        idcol = "Dataset")
    }), 
    idcol = "DS")

avg_jaccard_dists <-
    melt(jaccard_dists, 
         id.vars = c("DS", "Dataset", "Method"), 
         variable.name = "Method2", 
         value.name = "Jdist")[, c("SetSize", "MZP", "DsType", 
                                   "DsId") := tstrsplit(Dataset, "_"), 
                               by = Dataset][, .(AvgJDist = mean(Jdist)), 
                                             by = .(DS, SetSize, MZP, DsType, 
                                                    Method, Method2)]
```

```{r, warning=FALSE}
library(patchwork)
# install.packages("ggdendro")
library(ggdendro)
library(ggplot2)
library(scales)

avg_jaccard_dists_l <- split(avg_jaccard_dists, by = c("DS", "SetSize"), flatten = F, keep.by = F)

method_names <- sort(unique(avg_jaccard_dists_l$DM1$N10$Method))
method_colors <- setNames(hue_pal()(length(method_names)), method_names)

# x <- avg_jaccard_dists_l$DM1$N10
# ggdendrogram(hclust(as.dist(data.frame(dcast(setSize, 
#                                              Method ~ Method2, 
#                                              value.var = "AvgJDist"), 
#                                        row.names = "Method"))))

ggd_l <- 
    lapply(avg_jaccard_dists_l, function(ds){
        lapply(ds, function(setSize){
            ddata <- 
                dendro_data(as.dendrogram(hclust(as.dist(data.frame(dcast(setSize, 
                                                                          Method ~ Method2, 
                                                                          value.var = "AvgJDist"), 
                                                                    row.names = "Method")))), 
                            type = "rectangle")
            
            ggplot(segment(ddata), aes(x = x, y = y)) +
                geom_segment(aes(xend = xend, yend = yend)) +
                scale_x_continuous(name = NULL, breaks = label(ddata)$x, 
                                   labels = label(ddata)$label, 
                                   position = "top") +
                scale_y_reverse(name = "Jaccard distance", expand = c(0, 0.01)) +
                coord_flip() +
                theme_minimal() +
                theme(axis.text.y = element_text(color = method_colors[label(ddata)$label]),
                      panel.grid.major.x = element_blank(),
                      panel.grid.minor.x = element_blank(),
                      panel.grid.major.y = element_blank(),
                      panel.grid.minor.y = element_blank())
        })
        
    })
```

```{r, fig.height=16, fig.width=10}
gg_rows <- lapply(setNames(ds_names, nm = ds_names), 
                  function(x, ggd_l){
                      ggd_l[[x]]$N03 + ggtitle(paste(x, "N03")) +
                          ggd_l[[x]]$N05 + ggtitle(paste(x, "N05")) +
                          ggd_l[[x]]$N10 + ggtitle(paste(x, "N10"))
                  }, 
                  ggd_l = ggd_l)

gg_rows$DM1 / gg_rows$IPF / gg_rows$MS / gg_rows$IDC
```

## Average Jaccard per set size

```{r, warning=FALSE}
plots <- 
    lapply(split(avg_jaccard_dists[, .(AvgJDist = mean(AvgJDist)), 
                                   by = .(SetSize, MZP, DsType, Method, Method2)], 
                 by = c("SetSize"), flatten = F, keep.by = F), 
           function(setSize){
               ddata <- 
                   dendro_data(as.dendrogram(hclust(as.dist(data.frame(dcast(setSize, 
                                                                             Method ~ Method2, 
                                                                             value.var = "AvgJDist"), 
                                                                       row.names = "Method")))), 
                               type = "rectangle")
               
               ggplot(segment(ddata), aes(x = x, y = y)) +
                   geom_segment(aes(xend = xend, yend = yend)) +
                   scale_x_continuous(name = NULL, breaks = label(ddata)$x, 
                                      labels = label(ddata)$label, 
                                      position = "top") +
                   scale_y_reverse(name = "Jaccard distance", expand = c(0, 0.01)) +
                   coord_flip() +
                   theme_minimal() +
                   theme(axis.text.y = element_text(color = method_colors[label(ddata)$label]),
                         panel.grid.major.x = element_blank(),
                         panel.grid.minor.x = element_blank(),
                         panel.grid.major.y = element_blank(),
                         panel.grid.minor.y = element_blank())
           })

plots$N03  + 
    ggtitle("N03") + 
    theme(axis.text.x = element_text(angle = -35, hjust = .5, vjust = -1)) +
    plots$N05 + 
    ggtitle("N05") + 
    theme(axis.text.x = element_text(angle = -35, hjust = .5, vjust = -1)) +
    plots$N10 + 
    ggtitle("N10") + 
    theme(axis.text.x = element_text(angle = -35, hjust = .5, vjust = -1))
```

## Average Jaccard per data set

```{r, warning=FALSE, fig.height=10}
plots <- 
    lapply(split(avg_jaccard_dists[, .(AvgJDist = mean(AvgJDist)), 
                                   by = .(DS, MZP, DsType, Method, Method2)], 
                 by = c("DS"), flatten = F, keep.by = F), 
           function(setSize){
               ddata <- 
                   dendro_data(as.dendrogram(hclust(as.dist(data.frame(dcast(setSize, 
                                                                             Method ~ Method2, 
                                                                             value.var = "AvgJDist"), 
                                                                       row.names = "Method")))), 
                               type = "rectangle")
               
               ggplot(segment(ddata), aes(x = x, y = y)) +
                   geom_segment(aes(xend = xend, yend = yend)) +
                   scale_x_continuous(name = NULL, breaks = label(ddata)$x, 
                                      labels = label(ddata)$label, 
                                      position = "top") +
                   scale_y_reverse(name = "Jaccard distance", expand = c(0, 0.01)) +
                   coord_flip() +
                   theme_minimal() +
                   theme(axis.text.y = element_text(color = method_colors[label(ddata)$label]),
                         panel.grid.major.x = element_blank(),
                         panel.grid.minor.x = element_blank(),
                         panel.grid.major.y = element_blank(),
                         panel.grid.minor.y = element_blank())
           })

plots$DM1  + 
    ggtitle("DM1") + 
    theme(axis.text.x = element_text(angle = -35, hjust = .5, vjust = -1)) +
    plots$IPF + 
    ggtitle("IPF") + 
    theme(axis.text.x = element_text(angle = -35, hjust = .5, vjust = -1)) +
    plots$IDC + 
    ggtitle("IDC") + 
    theme(axis.text.x = element_text(angle = -35, hjust = .5, vjust = -1)) +
    plots$MS + 
    ggtitle("MS") + 
    theme(axis.text.x = element_text(angle = -35, hjust = .5, vjust = -1))
```

## Overall average

```{r, warning=FALSE, fig.width=2.5}
plot <- avg_jaccard_dists[, .(AvgJDist = mean(AvgJDist)), 
                          by = .(Method, Method2)]

ddata <- 
    dendro_data(as.dendrogram(hclust(as.dist(data.frame(dcast(plot, 
                                                              Method ~ Method2, 
                                                              value.var = "AvgJDist"), 
                                                        row.names = "Method")
                                             ), 
                                     method = "complete")
                              ), 
                type = "rectangle")

ggplot(segment(ddata), aes(x = x, y = y)) +
    geom_segment(aes(xend = xend, yend = yend)) +
    scale_x_continuous(name = NULL, breaks = label(ddata)$x, 
                       labels = label(ddata)$label, 
                       position = "top") +
    scale_y_reverse(name = "Jaccard distance", expand = c(0, 0.01)) +
    coord_flip() +
    theme_minimal() + 
    ggtitle("Overall average") + 
    theme(axis.text.y = element_text(color = method_colors[label(ddata)$label]),
          axis.text.x = element_text(angle = -35, hjust = .5, vjust = -1),
          panel.grid.major.x = element_blank(),
          panel.grid.minor.x = element_blank(),
          panel.grid.major.y = element_blank(),
          panel.grid.minor.y = element_blank())
```

# Session info

```{r}
sessionInfo()
```

