---
title: "Evaluate benchmark results"
author: "Enrico Gaffo"
date: "`r Sys.Date()`"
output: 
  html_document: 
    toc: yes
    toc_float: yes
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# library(SummarizedBenchmark)

library(data.table)
library(qs)
library(DT)
library(ComplexHeatmap)
library(scales)
library(ggplot2)
library(ggrepel)

library(BiocParallel)
```

```{r}
## output file path
output_dir <- "sim_ds_chars"
dir.create(path = output_dir, showWarnings = F, recursive = T)

## input data
ds_names <- c("DM1", "IDC", "IPF", "MS")
simulated_datasets_qs_files <- file.path(paste0(ds_names, "_prep_ds"), 
                                         "datasetList.qs")
names(simulated_datasets_qs_files) <- ds_names
```

```{r}
nWorkers <- multicoreWorkers()
```

```{r read_sim_datasets}
## read input: the simulated dataset list
sim_ds_list <- lapply(simulated_datasets_qs_files, 
                      qread, 
                      nthreads = nWorkers)
```

# Are matrix zero-inflated?

```{r, warning=FALSE}
melt_cnt <- rbindlist(lapply(sim_ds_list, 
                        function(sims) {
                            rbindlist(lapply(sims, 
                                             function(x) {
                                                 melt(as.data.table(x$cntdat))
                                             }), 
                                      use.names = T, idcol = "dataset")
                        }), idcol = "DS")

melt_cnt[, c("SetSize", "MZP", "Purpose", "ID") := tstrsplit(dataset, "_", type.convert = F), 
          by = dataset]
melt_cnt <- melt_cnt[MZP == "bulk"]

# ggplot(melt_cnt, aes(x = value)) +
#     geom_density(aes(group = dataset, color = Purpose)) +
#     facet_grid(cols = vars(SetSize), rows = vars(DS), scales = "free") +
#     coord_cartesian(xlim = c(0, 15)) +
#     theme(legend.position = "top")
```

```{r}
library(scales)

hist_cnt <- 
    melt_cnt[, .(histBJR = .N), 
             by = .(DS, dataset, SetSize, MZP, Purpose, ID, 
                    BJR = value)][, Frac := histBJR / sum(histBJR), 
                                  by = .(DS, dataset, SetSize, MZP, Purpose, ID)][]
plot_dt <- hist_cnt[, .(AvgFrac = mean(Frac),
                        sdFrac = sd(Frac)),
                    by = .(DS, SetSize, MZP, BJR)] #, Purpose

# plot_dt[is.na(sdFrac), sdFrac := 0]

ggplot(plot_dt, aes(x = BJR, y = AvgFrac)) + #, color = Purpose, fill = Purpose
    geom_errorbar(aes(ymin = AvgFrac - sdFrac, ymax = AvgFrac + sdFrac), width = .6) +
    geom_col(position = "identity", alpha = .5) +
    facet_grid(cols = vars(SetSize), rows = vars(DS), scales = "free") +
    coord_cartesian(xlim = c(0, 15)) +
    scale_y_continuous("Count matrix fraction (%)", 
                       labels = function(x)round(as.numeric(x)*100)) + #labels = percent
    scale_x_continuous(breaks = 0:15, 
                       labels = 0:15) +
    theme_classic() +
    theme(legend.position = "top", 
          axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5))
```



```{r}
sim_ds_dt <- rbindlist(lapply(sim_ds_list, 
                        function(sims) {
                            rbindlist(lapply(sims, 
                                             function(x) {
                                                 data.frame(circ_id = rownames(x$cntdat), 
                                                            AvgBJR = rowMeans(x$cntdat),
                                                            FracZeros = rowSums(x$cntdat == 0) / ncol(x$cntdat),
                                                            is.DEC = x$status)
                                             }), 
                                      use.names = T, idcol = "dataset")
                        }), idcol = "DS")

sim_ds_dt[, c("SetSize", "MZP", "Purpose", "ID") := tstrsplit(dataset, "_", type.convert = F), 
          by = dataset]
sim_ds_dt <- sim_ds_dt[MZP == "bulk"]
```

# DE simulated data sets 

## Raw expression {.tabset}

### Density multi lines

```{r}
p <- ggplot(data = sim_ds_dt[Purpose == "de"],
            mapping = aes(x = AvgBJR, color = factor(is.DEC))) +
    geom_density(aes(group = paste(dataset, is.DEC))) +
    scale_x_log10() +
    facet_wrap(DS ~ SetSize, 
               # scales = "free_y", 
               ncol = 3, 
               labeller = label_wrap_gen(multi_line = F)) +
    scale_color_discrete("DEC") +
    labs(y = "density") +
    theme_bw() +
    theme(legend.position = "top")
p
```

### Density sahdes ggplot2 stats

```{r}
ld <- as.data.table(layer_data(p))

ld.densities.qtiles <-
    ld[, as.list(c(quantile(y, probs = c(.025, .5, .975)), 
                          Mean = mean(y))), 
       by = .(colour, PANEL, x)]
ld.densities.qtiles[, DEC := ifelse(colour == "#F8766D", F, T)]

ld.densities.qtiles <-
    merge(ld.densities.qtiles, 
          sim_ds_dt[, .N, by = .(DS, SetSize)][, .(PANEL = factor(.I), DS = paste(DS, SetSize))],
          by = "PANEL")


ggplot(ld.densities.qtiles, 
       aes(x = x, y = `50%`)) + #Mean
    facet_wrap(~ DS, 
               # scales = "free", 
               ncol = 3) +
    # geom_histogram(data = sim_ds_dt[Purpose == "de"],
    #                aes(x = AvgBJR, y = ..density..), 
    #                fill = "white",
    #                binwidth = 0.25, boundary = 0) +
    geom_ribbon(aes(ymin = `2.5%`, ymax = `97.5%`, 
                    fill = DEC), 
                alpha = 0.5) +
    geom_line(aes(color = DEC)) +
    scale_color_discrete("DEC") +
    scale_fill_discrete("DEC") +
    labs(y = "density", x = "Log10(AvgBJR)") +
    theme_bw() +
    theme(legend.position = "top")
```

### Density sahdes custom stats

```{r}
#https://stackoverflow.com/questions/45908120/add-shaded-standard-error-curves-to-geom-density-in-ggplot2
plot_dt <- copy(sim_ds_dt)[, AvgBJR := log10(AvgBJR)][Purpose == "de"]

plot_dt[, `:=` (maxBJR = max(AvgBJR, na.rm = T),
                  minBJR = min(AvgBJR, na.rm = T),
                  len = length(AvgBJR)),
          by = .(MZP, Purpose)] #, DS, SetSize

densities <- 
    plot_dt[, data.frame(broom::tidy(stats::density(x = AvgBJR, 
                                                    # weights = rep(1 / length(AvgBJR), length(AvgBJR)),
                                                    from = min(minBJR, na.rm = T), 
                                                    to = max(maxBJR, na.rm = T),
                                                    bw = "nrd0", #"SJ"
                                                    adjust = 1,
                                                    kernel = "gaussian",
                                                    n = 512,
                                                    na.rm = TRUE))),
              by = .(DS, SetSize, Purpose, ID, DEC = ifelse(is.DEC == 1, T, F))]

densities.qtiles <-
    densities[, as.list(c(quantile(y, probs = c(.025, .5, .975)), 
                          Mean = mean(y))),
              by = .(DS, SetSize, DEC, AvgBJR = x)]

ggplot(densities.qtiles, 
       aes(x = AvgBJR, y = Mean)) + #`50%`
    facet_wrap(DS ~ SetSize, 
               # scales = "free",
               ncol = 3, 
               labeller = label_wrap_gen(multi_line = F)) +
    # geom_histogram(data = sim_ds_dt[Purpose == "de"],
    #                aes(x = AvgBJR, y = ..density..), 
    #                fill = "white",
    #                binwidth = 0.25, boundary = 0) +
    geom_ribbon(aes(ymin = `2.5%`, ymax = `97.5%`, 
                    fill = DEC), 
                alpha = 0.5) +
    # stat_density(data = sim_ds_dt[Purpose == "de"],
    #              aes(AvgBJR, ..density.., color = "raw density"),
    #              size = 2, geom = "line") +
    geom_line(aes(color = DEC)) +
    scale_color_discrete("DEC") +
    scale_fill_discrete("DEC") +
    labs(y = "density", x = "Log10(AvgBJR)") +
    theme_bw() +
    theme(legend.position = "top")
```

## DEC Fraction of zeros density

```{r}
ggplot(sim_ds_dt, aes(x = FracZeros, color = ifelse(is.DEC == 1, T, F))) +
    # geom_density(aes(group = paste(dataset, is.DEC)), alpha = .3) +
    geom_histogram(aes(y = ..ndensity.., 
                       fill = ifelse(is.DEC == 1, T, F)),
                   position = "identity",
                   alpha = .5, binwidth = .1) +
    scale_color_discrete("DEC") +
    scale_fill_discrete("DEC") +
    facet_grid(cols = vars(SetSize), rows = vars(DS)) + 
    theme_bw() +
    theme(legend.position = "top", 
          axis.text.x = element_text(angle = 30, hjust = 1))
```

```{r}
# plot_dt <- copy(sim_ds_dt)[Purpose == "de"]
# 
# # plot_dt[, `:=` (maxFZ = max(FracZeros, na.rm = T),
# #                   minFZ = min(FracZeros, na.rm = T),
# #                   len = length(FracZeros)),
# #           by = .(MZP, Purpose)] #, DS, SetSize
# 
# fz_densities <- 
#     plot_dt[, data.frame(broom::tidy(stats::density(x = FracZeros, 
#                                                     # weights = rep(1 / length(AvgBJR), length(AvgBJR)),
#                                                     from = 0, 
#                                                     to = 1,
#                                                     bw = .1, #"nrd0", #"SJ"
#                                                     adjust = 1,
#                                                     kernel = "gaussian",
#                                                     n = 512,
#                                                     na.rm = TRUE))),
#               by = .(DS, SetSize, Purpose, ID, DEC = ifelse(is.DEC == 1, T, F))]
# 
# fz_densities.qtiles <-
#     fz_densities[, as.list(c(quantile(y, probs = c(.025, .5, .975)), 
#                           Mean = mean(y))),
#               by = .(DS, SetSize, DEC, FracZeros = x)]
# 
# ggplot(fz_densities.qtiles, 
#        aes(x = FracZeros, y = Mean, fill = DEC)) + #`50%`
#     facet_wrap(DS ~ SetSize, 
#                # scales = "free",
#                ncol = 3, 
#                labeller = label_wrap_gen(multi_line = F)) +
#     geom_histogram(data = sim_ds_dt[Purpose == "de"][, DEC := ifelse(is.DEC == 1, T, F)],
#                    aes(x = FracZeros, y = ..ndensity..),
#                    # fill = "white",
#                    binwidth = 0.1, alpha = .5) + #boundary = 0,
#     # geom_ribbon(aes(ymin = `2.5%`, ymax = `97.5%`), 
#     #             alpha = 0.5) +
#     # geom_line(aes(color = DEC)) +
#     scale_color_discrete("DEC") +
#     scale_fill_discrete("DEC") +
#     labs(y = "density", x = "Zero faction") +
#     theme_bw() +
#     theme(legend.position = "top")
```

## Raw expression vs fraction of zeros

```{r}
# library(ggrastr)
# plot_dt <- sim_ds_dt[][, DEC := ifelse(is.DEC == 1, T, F)]
# ggplot(plot_dt, aes(x = AvgBJR, y = FracZeros, color = DEC)) +
#     # geom_point_rast() +
#     # geom_density_2d() +
#     geom_smooth() +
#     scale_x_log10() +
#     facet_grid(cols = vars(SetSize), rows = vars(DS)) + 
#     theme_bw() +
#     theme(legend.position = "top", 
#           axis.text.x = element_text(angle = 30, hjust = 1))
```

## CircRNA counts

```{r}
ncircs <- sim_ds_dt[Purpose == "de", .N, 
                 by = .(DS, SetSize, ID, 
                        DEC = ifelse(is.DEC == 1, T, F))]

ggplot(ncircs,
       aes(x = SetSize, y = N, color = DEC)) +
    geom_boxplot() +
    scale_y_log10("Simulated circRNAs") +
    facet_wrap(~ DS, 
               # scales = "free_y", 
               dir = "v") +
    theme_bw() +
    theme(legend.position = "top")
```

```{r}
datatable(dcast(ncircs, DS + SetSize + ID ~ DEC)[, Tot := `FALSE` + `TRUE`][], 
          rownames = F, filter = "top")
```

```{r}
datatable(ncircs[, as.list(summary(N)), by = .(DS, SetSize)], 
          rownames = F, filter = "top")
```

```{r}
datatable(ncircs[, as.list(summary(N)), by = .(DS, SetSize, DEC)], 
          rownames = F, filter = "top")
```

# Mock 

```{r}
ncircs <- sim_ds_dt[Purpose == "mock", .N, 
                 by = .(DS, SetSize, ID)]

ggplot(ncircs,
       aes(x = SetSize, y = N)) +
    geom_boxplot() +
    scale_y_log10("Simulated circRNAs") +
    facet_wrap(~ DS, 
               # scales = "free_y", 
               dir = "v") +
    theme_bw() +
    theme(legend.position = "top")
```

```{r}
datatable(ncircs[, as.list(summary(N)), by = .(DS, SetSize)], 
          rownames = F, filter = "top")
```

# Session info

```{r}
sessionInfo()
```

