---
title: "Update Summarized Benchmarks"
author: "Enrico Gaffo"
date: "`r Sys.Date()`"
output: 
  html_document: 
    toc: yes
    toc_float: yes
    code_folding: hide
params:
  outdir: "DM1_updated_benchmark_results"
  inputData: "./DM1_benchmark_results/sumBenchs.qs"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(SummarizedBenchmark)
library("magrittr")
# library(plotROC)
library(data.table)
library(qs)
library(DT)

library("limma")
library("edgeR")
library("DESeq2")
library("tximport")
library(glmGamPoi)
library(zinbwave)
library(scran)

library(BiocParallel)
library(batchtools)

# install.packages("devtools", Ncpus = multicoreWorkers())
# library(devtools)
# install_github("lichen-lab/circMeta", Ncpus = multicoreWorkers())
library(circMeta)
# library(lncDIFF)
# library(ShrinkBayes)
# library(samr)
```

```{r}
## set the output directory
# outdir <- "benchmark_results"
outdir <- params$outdir
dir.create(path = outdir, recursive = T, showWarnings = F)
```

```{r}
nWorkers <- multicoreWorkers()

## load previous benchmark
inputData <- params$inputData
sbL <- qread(file = inputData, nthreads = nWorkers)
```

```{r}
# subsetIdx <- c(1:2, 31:32, 61:62, 91:92, 121:122, 151:152)
# subsetIdx <- 1:2
subsetIdx <- 1:length(sbL) # all
sbL <- sbL[subsetIdx]
```

```{r}
## set scheduler for cluster computing
ncpus <- 1
bpparam <- BatchtoolsParam(workers = length(sbL), 
                           saveregistry = F,
                           cluster = "slurm",
                           resources = list(ncpus = ncpus, 
                                            walltime = 3600, # 1h max
                                            memory = 8192) # 4Gb, 2048 2GByte, 8192 8Gb
)

## Multithread, single machine
# bpparam <- MulticoreParam(nWorkers)
```

# Update bench design

## Add lncDIFF method(s)

```{r}
lncdiff_run <- function(countData, group) {
  
  tictoc::tic()
      
  res <- lncDIFF::lncDIFF(edata = countData, 
                          group = as.character(group), 
                          covariate = NULL, 
                          link.function = 'log', 
                          CompareGroups = unique(as.character(group)),
                          simulated.pvalue = FALSE, 
                          permutation = 100)
  
  runtime <- tictoc::toc(log = F, quiet = T)
  
  list(res = res, 
       runtime = runtime$toc - runtime$tic)
  
}

lncdiff_pv <- function(x) {
  x$res$DE.results$Pvalue
}


lncdiff_apv <- function(x) {
  p.adjust(x$res$DE.results$Pvalue, method = "BH")
}

lncdiff_lfc <- function(x) {
  x$res$DE.results$Log2.Fold.Change
}

lncdiff_time <- function(x) { rep(as.numeric(x$runtime), length(x$res$DE.results$Pvalue)) }
```

### Update the Build bench list

```{r}
# https://www.bioconductor.org/packages/devel/bioc/vignettes/SummarizedBenchmark/inst/doc/Feature-Iterative.html#using-updatebench
## override BPPARAM
parallel_methods <- 4
bpparam$resources$ncpus <- parallel_methods

func_list <- list(lncdiff_run = lncdiff_run,
                  lncdiff_pv = lncdiff_pv,
                  lncdiff_apv = lncdiff_apv,
                  lncdiff_lfc = lncdiff_lfc,
                  lncdiff_time = lncdiff_time)

sbL <- 
    bplapply(sbL, 
             function(sb, 
                      func_list,
                      parallel_methods) { 
                 bd <- SummarizedBenchmark::BenchDesign(sb)
                 
                 bd <- SummarizedBenchmark::addMethod(bd = bd,
                                                      label = "lncDIFF_Dt_LRT", 
                                                      func = func_list$lncdiff_run, 
                                                      post = list(pv = func_list$lncdiff_pv,
                                                                  adj_pv = func_list$lncdiff_apv,
                                                                  lfc = func_list$lncdiff_lfc,
                                                                  runtime = func_list$lncdiff_time),
                                                      meta = list(pkg_name = "lncDIFF", 
                                                                  pkg_vers = as.character(packageVersion("lncDIFF"))),
                                                      params = rlang::quos(countData = cntdat,
                                                                           group = coldat$condition))
                 
                 SummarizedBenchmark::updateBench(sb = sb, bd = bd, dryrun = F)
             }, 
             func_list = func_list,
             parallel_methods = parallel_methods,
             BPPARAM = bpparam)
# sbL
```

```{r}
## error handling
show_dt <- 
  dcast(melt(rbindlist(lapply(sbL, 
                              function(x)data.table(as.data.frame(simplify2array(metadata(x)$sessions[[1]]$results)), 
                                                    keep.rownames = "Assay")), 
                       idcol = "DS"), 
             id.vars = c("DS", "Assay"), 
             variable.name = "Method"), 
        formula = DS + Method ~ Assay)

show_dt$DS <- factor(show_dt$DS)
show_dt$Method <- factor(show_dt$Method)

datatable(show_dt[adj_pv != "success" | 
                    lfc != "success" | 
                    pv != "success" | 
                    runtime != "success"], 
          caption = "Methods that failed",
          filter = "top", rownames = F)
```

```{r}
## save the updated summarizedBenchmark
sumBench_perf_metrics_qs <- file.path(outdir, "updated_sumBenchs.qs")
qsave(x = sbL, 
      file = sumBench_perf_metrics_qs, 
      nthreads = multicoreWorkers(), 
      preset = "fast")
```

## Add SAMseq method(s)

```{r}
samseq_run <- function(countData, group) {
  
  library(samr)
  
  tictoc::tic()
  
  condition.12 <- rep(1, length(group))
  condition.12[which(group == levels(factor(group))[2])] <- 2
  
  SAMseq.test <- samr::SAMseq(countData, 
                              condition.12, 
                              resp.type = 'Two class unpaired', 
                              geneid = rownames(countData), 
                              genenames = rownames(countData), 
                              nperms = 100, 
                              nresamp = 20,
                              fdr.output = 1)
  pv <- samr.pvalues.from.perms(tt = SAMseq.test$samr.obj$tt, 
                                ttstar = SAMseq.test$samr.obj$ttstar)
  
  SAMseq.result <- rbind(SAMseq.test$siggenes.table$genes.up,
                         SAMseq.test$siggenes.table$genes.lo)
  
  SAMseq.statistic <- rep(0, nrow(countData))
  
  SAMseq.statistic[match(SAMseq.result[, 1], 
                         rownames(countData))] <- as.numeric(SAMseq.result[, 3])
  
  SAMseq.FDR <- rep(1, nrow(countData))
  
  SAMseq.FDR[match(SAMseq.result[, 1], 
                   rownames(countData))] <- as.numeric(SAMseq.result[, 5]) / 100
  
  SAMseq.FC <- rep(NA, nrow(countData))
  
  SAMseq.FC[match(SAMseq.result[, 1], 
                   rownames(countData))] <- as.numeric(SAMseq.result[, 4])
  
  SAMseq.score <- 1 - SAMseq.FDR
  
  res <- data.frame('statistic' = SAMseq.statistic, 
                    'Pvalue' = pv,
                    'FDR' = SAMseq.FDR, 
                    'FC' = SAMseq.FC,
                    'score' = SAMseq.score)
  
  runtime <- tictoc::toc(log = F, quiet = T)
  
  list(res = res, 
       runtime = runtime$toc - runtime$tic)
}

samseq_pv <- function(x) {
  x$res$Pvalue
}


samseq_apv <- function(x) {
  # p.adjust(x$res$Pvalue, "BH")
  x$res$FDR
}

samseq_lfc <- function(x) {
  log2(x$res$FC)
}

samseq_time <- function(x) { rep(as.numeric(x$runtime), nrow(x$res)) }
```

```{r}
## make a new Bench Design
# bd <- BenchDesign()
# 
# bd <- bd %>%
#     addMethod(label = "SAMseq_Dt_TT", ## lncDIFF, defaults, test?
#               func = samseq_run,
#               post = list(pv = samseq_pv,
#                           adj_pv = samseq_apv,
#                           lfc = samseq_lfc,
#                           runtime = samseq_time),
#               meta = list(pkg_name = "samr", pkg_vers = as.character(packageVersion("samr"))),
#               params = rlang::quos(countData = cntdat,
#                                    group = coldat$condition))
```

### Update the Build bench list

```{r}
# https://www.bioconductor.org/packages/devel/bioc/vignettes/SummarizedBenchmark/inst/doc/Feature-Iterative.html#using-updatebench
## override BPPARAM
parallel_methods <- 4
bpparam$resources$ncpus <- parallel_methods

func_list <- list(samseq_run = samseq_run,
                  samseq_pv = samseq_pv,
                  samseq_apv = samseq_apv,
                  samseq_lfc = samseq_lfc,
                  samseq_time = samseq_time)

sbL <- 
    bplapply(sbL, 
             function(sb, 
                      func_list,
                      parallel_methods) { 
                 bd <- SummarizedBenchmark::BenchDesign(sb)
                 
                 bd <- SummarizedBenchmark::addMethod(bd = bd,
                                                      label = "SAMseq_Dt_TT", 
                                                      func = func_list$samseq_run,
                                                      post = list(pv = func_list$samseq_pv,
                                                                  adj_pv = func_list$samseq_apv,
                                                                  lfc = func_list$samseq_lfc,
                                                                  runtime = func_list$samseq_time),
                                                      meta = list(pkg_name = "samr", 
                                                                  pkg_vers = as.character(packageVersion("samr"))),
                                                      params = rlang::quos(countData = cntdat,
                                                                           group = coldat$condition))
                 
                 SummarizedBenchmark::updateBench(sb = sb, bd = bd, dryrun = F)
             }, 
             func_list = func_list,
             parallel_methods = parallel_methods,
             BPPARAM = bpparam)
# sbL
```

```{r}
## error handling
show_dt <- 
  dcast(melt(rbindlist(lapply(sbL, 
                              function(x)data.table(as.data.frame(simplify2array(metadata(x)$sessions[[1]]$results)), 
                                                    keep.rownames = "Assay")), 
                       idcol = "DS"), 
             id.vars = c("DS", "Assay"), 
             variable.name = "Method"), 
        formula = DS + Method ~ Assay)

show_dt$DS <- factor(show_dt$DS)
show_dt$Method <- factor(show_dt$Method)

datatable(show_dt[adj_pv != "success" | 
                    lfc != "success" | 
                    pv != "success" | 
                    runtime != "success"], 
          caption = "Methods that failed",
          filter = "top", rownames = F)
```

```{r}
## save the updated summarizedBenchmark
sumBench_perf_metrics_qs <- file.path(outdir, "updated_sumBenchs.qs")
qsave(x = sbL, 
      file = sumBench_perf_metrics_qs, 
      nthreads = multicoreWorkers(), 
      preset = "fast")
```

The benchmark results have been save into <a href="`r sumBench_perf_metrics_qs`">`r sumBench_perf_metrics_qs`</a>.  

## ShrinkBayes

```{r}
shrinkBayes_run <- 
    function(countData, groups) {
      
      ## TODO: complete this function
        
      tictoc::tic()
      
      ## https://github.com/markvdwiel/ShrinkBayes/blob/master/inst/doc/ShrinkBayes.pdf
      # library(edgeR)
      DGE <- edgeR::DGEList(countData, group = groups)
      libsize <- colSums(countData, na.rm = T)
      DGEnorm <- edgeR::calcNormFactors(DGE, method = "TMMwsp")
      normfac0 <- DGEnorm$samples[,3]
      rellibsize <- libsize / exp(mean(log(libsize)))
      normfac <- normfac0 * rellibsize
      myoffsets <- log(normfac)
      form <- ~ 1 + groups + offset(myoffsets)
      # form0 <- ~ 1 + offset(myoffsets)
      
      library(INLA)
      library(ShrinkBayes)
      SBmir <- ShrinkBayes::ShrinkBayesWrap(countData, form, ncpus = 1)
      # shrinksimul <- ShrinkSeq(form = form,
      #                          dat = countData,
      #                          shrinkfixed = "g",
      #                          fams = "zinb")
      
      # form0 <- y ~ 1
      # shrinksimul <- ShrinkSeq(form = form, 
      #                          dat = physeq@otu_table@.Data, 
      #                          shrinkfixed = "g", 
      #                          fams = "zinb")
      # fitall <- FitAllShrink(form, 
      #                        dat = norm.counts, 
      #                        fams = "zinb",
      #                        shrinksimul = shrinksimul)
      # fitall0 <- FitAllShrink(form0, 
      #                         dat = norm.counts, 
      #                         fams = "zinb",
      #                         shrinksimul = shrinksimul)  
      # npprior <- MixtureUpdatePrior(fitall = fitall, 
      #                               fitall0 = fitall0, 
      #                               shrinkpara="g", 
      #                               ncpus = mc.cores)
      # nppostshr <- MixtureUpdatePosterior(fitall, npprior, fitall0)
      # lfdr <- SummaryWrap(nppostshr)
      # fdr <- BFDR(lfdr)
      # pGlobal <- as.vector(fdr)
      # rm(list = c("ptm", "g", "form", "form0", "shrinksimul", 
      #             "fitall", "fitall0", "npprior" ,"nppostshr", "lfdr", "fdr"))
      # 
      # pValMat <- as.matrix(pGlobal)
      # colnames(pValMat) <- c("adjP")
      # statInfo <- NULL
      
      res <- list("pValMat" = pValMat, "statInfo" = statInfo)
      # res <- data.frame(p.value = pval, 
      #               logFC = lfc)
      
      runtime <- tictoc::toc(log = F, quiet = T)
      
      list(res = res, 
           runtime = runtime$toc - runtime$tic)
    }

#TODO
shrinkBayes_pv <- function(x) {}

shrinkBayes_apv <- function(x) {}

shrinkBayes_lfc <- function(x) {}

shrinkBayes_time <- function(x) { x$runtime }
```

## Other

```{r}
# poissonSeq <- function(countData, group, design) {
#     library(PoissonSeq)
#     dat = list(n = count.matrix(cdata), 
#                y=sample.annotations(cdata)$condition, 
#                pair = FALSE, 
#                type = 'twoclass', 
#                gname=rownames(count.matrix(cdata)))
#     PS.test = PoissonSeq::PS.Main(dat)
#     PS.nc = PS.test$nc
#     PS.gname = rownames(PS.test)
#     PS.tt = PS.test$tt
#     PS.pvalue = PS.test$pval
#     PS.FDR = PS.test$fdr
#     PS.logfc =  PS.test$log.fc
#     result.table = data.frame('nc' = PS.nc, 
#     'Genename' = PS.gname, 
#     'tt' = PS.tt, 
#     'pvalue' = PS.pvalue, 
#     'FDR'=PS.FDR, 'log.fc' = PS.logfc)
# }

# ROTS <- function(countData, group, design) {
#     library(ROTS)
#     log=F
#     transformation<-T
#     normalize<-T
#     if(normalize&&transformation){
#     if(transformation){
#       log=TRUE
#       nf <- edgeR::calcNormFactors(count.matrix(cdata), method = 'TMM' )
#       voom.data <- limma::voom(count.matrix(cdata),
#                                design = model.matrix(~factor(sample.annotations(cdata)$condition)),
#                                lib.size = colSums(count.matrix(cdata)) * nf)
#       Exp <- voom.data$E
#     }else{
#       edgeR.dgelist <- edgeR::DGEList(counts = count.matrix(cdata),
#                                       group = factor(sample.annotations(cdata)$condition))
#       edgeR.dgelist <- edgeR::calcNormFactors(edgeR.dgelist, method = 'TMM')
#       Factors <- edgeR.dgelist$samples$lib.size * edgeR.dgelist$samples$norm.factors
#       Exp <- t(t(edgeR.dgelist$counts)/Factors) * mean(Factors)
#     }
#   }else{
#     Exp <- count.matrix(cdata)
#   }
# 
# 
#   results <- ROTS::ROTS(data = Exp,
#                         groups = as.numeric(as.character(factor(sample.annotations(cdata)$condition))),
#                         K = NULL, B = 1000, log = log)
#   rots.pvalues <- results$pvalue
#   rots.logFC <- results$logfc
#   rots.FDR <- results$FDR
#   result.table <- data.frame('pvalue' = rots.pvalues, 'logFC' = rots.logFC, 'FDR' = rots.FDR)
# }

# baySeq <- function(countData, group, design) {
#     
#     baySeq.cd <- new('countData',
#                      data = countData,
#                      replicates = group,
#                      groups = list(NDE = rep(1, length(design)),
#                                    DE = design))
#     
#     libsizes(baySeq.cd) <- baySeq::getLibsizes(baySeq.cd, estimationType = "edgeR")
#     
#     baySeq.cd <- baySeq::getPriors.NB(baySeq.cd,
#                                       # samplesize = sample.size,
#                                       equalDispersions = TRUE,
#                                       estimation = "QL",
#                                       cl = NULL)
#     baySeq.cd <- baySeq::getLikelihoods.NB(baySeq.cd,
#                                            # prs = c(0.5, 0.5), 
#                                            pET = "BIC", 
#                                            cl = NULL)
#     baySeq.cd@annotation <- data.frame(rowID = rownames(baySeq.cd@data),
#                                        row.names = rownames(baySeq.cd@data))
#     baySeq.posteriors.DE <- exp(baySeq.cd@posteriors)[, 'DE']
#     baySeq.FDR <- baySeq::topCounts(baySeq.cd, group = 'DE',
#                                     FDR = 1)$FDR.DE[match(rownames(countData),
#                                                           rownames(baySeq::topCounts(baySeq.cd,
#                                                                                      group = 'DE', FDR = 1)))]
#     baySeq.score <- 1 - baySeq.FDR
#     data.frame('FDR' = baySeq.FDR, 'score' = baySeq.score, 'posterior.DE' = baySeq.posteriors.DE)
# }

# DeSingle_run <- function(countData, group, design) {
#   #Load library and the test data for DEsingle
#   library(DEsingle)
#   library(SingleCellExperiment)
#   data(TestData)
#   
#   # Convert the test data in DEsingle to SingleCellExperiment data representation
#   sce <- SingleCellExperiment(assays = list(counts = countData))
#   
#   # Detecting the DE genes with SingleCellExperiment input sce
#   results <- DEsingle(counts = sce, group = group)
#   
#   # Dividing the DE genes into 3 categories at threshold of FDR < 0.05
#   results.classified <- DEtype(results = results, threshold = 0.05)
#   
#   # Dividing the DE genes into 3 categories at threshold of FDR < 0.05
#   # results.classified <- DEtype(results = results, threshold = 1)
#   
#   # results$emdall
#   pValMat <- as.matrix(results$pvalue)
#   colnames(pValMat) <- c("adjP")
#   statInfo <- cbind("foldChange" = results$foldChange)
#   list("pValMat" = pValMat, "statInfo" = statInfo)
# }# END - function: DeSingle

# #TODO
# _apv <- function(x) {}
# 
# _lfc <- function(x) {}
# 
# _time <- function(x) {}
```


# Session info

```{r}
sessionInfo()
```

