\documentclass{article}
\usepackage[margin=2cm]{geometry}
\title{Sensitivity and precision using the DM1 dataset}
\author{Alessia Buratin}
\begin{document}
%\SweaveOpts{concordance=TRUE}
\maketitle

\section{Load the benchmarking results}

We load the benchmarking results, which were produced by the script 
\texttt{glm\_glmm\_paired.R}.

<<loadData>>=
basedir = "/blackhole/alessia/CircModel/"
# load(file = "/blackhole/alessia/CircModel/power/IPF_sensitivityPrecision_CCP2_glmglmm_30rep.RData")
load(file = "/blackhole/alessia/CircModel/robustness/ALZ_sensitivityPrecision_CCP2_glmglmm_30rep.RData.bk")

@ 

The evaluation set results are contained in the \texttt{resTes} object 
and the verification set results are contained in the \texttt{resHeldout} object,
each a list, one element for each random replicate, of data frames which contain
a column for each algorithm giving the adjusted $p$-values for each circRNA. 
For $p$-value adjustment, the \textit{p.adjust} function was used with 
\texttt{method="BH"} (Benjamini-Hochberg correction), 
over only those genes with non-zero row sum.

<<functions>>=
library("ggplot2")
library("reshape")
library("data.table")
library("dplyr")
alpha=.1
getCalls <- function(m, alpha=NULL) {
  t(sapply(1:nreps, function(i) sapply(namesAlgos, function(algo) {
    sum(m[[i]][[algo]][!is.na(m[[i]][[algo]])]<0.1)
    # sum((m[[i]][[algo]] < alpha))
  })))
}

getSensitivityAlgo <- function(m, alpha, alphaOut) {
  t(sapply(1:nreps, function(i) sapply(namesAlgosALL, function(algo) {
    sigHeldout <- resHeldout[[m]][[i]][[algo]] <= alpha
    mean((resTes[[m]][[i]][[algo]] <= alpha)[sigHeldout])
  })))
}

getPrecisionAlgo <- function(m, alpha, alphaOut) {
  t(sapply(1:nreps, function(i) sapply(namesAlgosALL, function(algo) {
    sigTest <- resTes[[m]][[i]][[algo]] <= alpha #Evaluation set
    if (sum(sigTest) == 0) return(0)
    mean((resHeldout[[m]][[i]][[algo]] <= alpha)[sigTest]) #TP rate
  })))
}

getSensitivityAlgoGold <- function(m, alpha, alphaOut, gold) {
  t(sapply(1:nreps, function(i) sapply(namesAlgosALL, function(algo) {
    sigHeldout <- resHeldoutALL[[m]][[i]][[gold]] < alphaOut
    mean((resTestALL[[m]][[i]][[algo]] < alpha)[!is.na(sigHeldout)])
  })))
}

getPrecisionAlgoGold <- function(m, alpha, alphaOut, gold) {
  t(sapply(1:nreps, function(i) sapply(namesAlgosALL, function(algo) {
    sigTest <- resTestALL[[m]][[i]][[algo]] < alpha
    if (sum(sigTest) == 0) return(0)
    mean((resHeldoutALL[[m]][[i]][[gold]] < alphaOut)[!is.na(sigTest)])
  })))
}
@ 

The following function helps to rename algorithms. 

<<renameAtoB>>=
renameAtoB <- function(f,a,b) {
  levels(f)[levels(f) == a] <- b
  f
}
@ 

<<namesAlgos>>=
namesAlgos <- make.names(names(resTes[[1]]))
names(namesAlgos) <- namesAlgos
@ 

<<colorAlgorithm>>=
library(RColorBrewer)
# display.brewer.all()

cols <- c(
  # DEseq
  brewer.pal(n = 9, "YlOrRd")[c(3,4,5,6)],
  # Edger
  brewer.pal(n = 9, name = "GnBu")[c(5,6,7)],
  # limma
  brewer.pal(n = 9, "RdPu")[c(5)],
  # circMeta
  brewer.pal(n = 9, "OrRd")[c(8)],
  # GLMM
  brewer.pal(n = 9, "BuPu")[c(5)]

)

methods2 <- c("DESeq2",
             "DESeq2-ZeroInflated",
             "DESeq2-GamPoi",
             "DESeq2-ZINB Wave",
             "edgeR",
             "edgeR-robust",
             "edgeR-ZINB Wave",
             "voom",
             "circMeta",
             "GLMM")

names(cols) <- methods2

@

\clearpage

\section{Counting number of calls}

Here we produce boxplots of the number of calls based on adjusted $p$-value
for each algorithm in the evaluation set and verification set for each random replicate.

<<countCalls>>=
nreps <- length(resHeldout)
nalgo <- length(namesAlgos)
# nmethods <- length(names(resHeldout))

heldMat <- getCalls(m = resHeldout, alpha = .1)
testMat <- getCalls(m = resTes, alpha = .1)

d <- data.frame(heldoutCalls=reshape2::melt(heldMat)$value,
                testCalls=reshape2::melt(testMat)$value,
                algorithm=factor(rep(namesAlgos,each=nrow(heldMat)),
                levels=namesAlgos))
                #detection.method=rep(factor(rep(names(resHeldout), each=nrow(heldMat))), nalgo))
d$algorithm <- renameAtoB(d$algorithm, "edgeR.robust", "edgeR-robust")
d$algorithm <- renameAtoB(d$algorithm, "edgeR.ZINBWave", "edgeR-ZINB Wave")
d$algorithm <- renameAtoB(d$algorithm, "DESeq2.ZINBWave", "DESeq2-ZINB Wave")
d$algorithm <- renameAtoB(d$algorithm, "DESeq2.ZI", "DESeq2-ZeroInflated")
d$algorithm <- renameAtoB(d$algorithm, "DESeq2.glmGamPoi", "DESeq2-GamPoi")
d$algorithm <- renameAtoB(d$algorithm, "GLMM_NB", "GLMM")

d$algorithm <- as.character(d$algorithm)

d <- d %>%
  mutate_if(sapply(d, is.character), as.factor)
d$heldoutCalls <- as.numeric(d$heldoutCalls)
d$testCalls <- as.numeric(d$testCalls)
@

<<testCalls, dev="pdf", fig.align="center", fig.width=8, fig.height=6, fig.cap="Evaluation set calls (adjusted $p$-value $< .1$)">>=
p <- ggplot(d, aes(x=reorder(algorithm,testCalls,median),y=testCalls,color=algorithm))
# png("/blackhole/alessia/CircModel/robustness/Figure/DEcalls_evaluation_ALZ.png", res = 200, units = "cm", width = 25, height = 15)
p + geom_boxplot(outlier.colour=rgb(0,0,0,0)) + theme_bw() +
    geom_point(position = position_jitter(w = 0.1, h = 0), color="grey50", size=1) +
    # facet_grid(.~detection.method) +
    scale_color_manual(values = cols, guide="none") +
    theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 12),
          axis.text.y = element_text(size = 9),
          axis.text.y.left = element_text(size = 12),
          strip.text.x = element_text(size = 9)) + xlab("") + 
    ylab("number of DE calls in Evaluation set")
# dev.off()
@ 

<<heldoutCalls, dev="pdf", fig.align="center", fig.width=8, fig.height=6, fig.cap="Verification set calls (adjusted $p$-value $< .1$)">>=
p <- ggplot(d, aes(x=reorder(algorithm,heldoutCalls,median),y=heldoutCalls,color=algorithm))
# png("/blackhole/alessia/CircModel/power/Figure/DEcalls_verification_ALZ.png", res = 200, units = "cm", width = 25, height = 15)
p + geom_boxplot(outlier.colour=rgb(0,0,0,0)) + theme_bw() +
    geom_point(position = position_jitter(w = 0.1, h = 0), color="grey50", size=1) +
    # facet_grid(.~detection.method) +
    scale_color_manual(values = cols, guide="none") +
    theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 12),
          axis.text.y = element_text(size = 9),
          axis.text.y.left = element_text(size = 12),
          strip.text.x = element_text(size = 9)) + xlab("") + 
    ylab("number of DE calls in Verification set")
# dev.off()
@ 

\clearpage

\section{Sensitivity and precision plots}

We construct a data frame containing the sensitivity and
precision estimates for every algorithm in the 
evaluation set and the verification set.

<<constructGrid>>=
nreps = 30
gold = "GLMM_NB"
alpha = .1 
alphaOut = .1
resHeldout = lapply(resHeldout, function(x){z=x[complete.cases(x),]
return(z)})
resTes = lapply(resTes, function(x){z=x[complete.cases(x),]
return(z)})

res = t(sapply(1:nreps, function(i) sapply(namesAlgos, function(algo) {
    sigHeldout <- resHeldout[[i]][[gold]] < alphaOut
    mean((resTes[[i]][[algo]] < alpha)[sigHeldout])
  })))

sensMat  = data.frame(res, heldout=rep("GLMM",nrow(res)))

sensMelt <- suppressWarnings(melt(sensMat, id=c("heldout")))
names(sensMelt) <- c("verification", "evaluation","sensitivity")

res = t(sapply(1:nreps, function(i) sapply(namesAlgos, function(algo) {
    sigTest <- resTes[[i]][[algo]] < alpha
    if (sum(sigTest) == 0) return(0)
    mean((resHeldout[[i]][[gold]] < alphaOut)[sigTest])
  })))
precMat = data.frame(res, heldout=rep("GLMM", nrow(res)))

precMelt <- suppressWarnings(melt(precMat, id=c("heldout")))
names(precMelt) <- c("verification", "evaluation","precision")

d <- data.frame(sensMelt, precision=precMelt$precision)
d$evaluation <- factor(d$evaluation)
d$verification <- factor(d$verification)
@ 

<<renameSensResults>>=
d$evaluation <- renameAtoB(d$evaluation, "edgeR.robust", "edgeR-robust")
d$verification <- renameAtoB(d$verification, "edgeR.robust", "edgeR-robust")
d$verification <- renameAtoB(d$verification, "edgeR.ZINBWave", "edgeR-ZINB Wave")
d$evaluation <- renameAtoB(d$evaluation, "edgeR.ZINBWave", "edgeR-ZINB Wave")
d$evaluation <- renameAtoB(d$evaluation, "DESeq2.ZINBWave", "DESeq2-ZINB Wave")
d$verification <- renameAtoB(d$verification, "DESeq2.ZINBWave", "DESeq2-ZINB Wave")
d$evaluation <- renameAtoB(d$evaluation, "DESeq2.glmGamPoi", "DESeq2-GamPoi")
d$verification <- renameAtoB(d$verification, "DESeq2.glmGamPoi", "DESeq2-GamPoi")
d$evaluation <- renameAtoB(d$evaluation, "DESeq2.ZI", "DESeq2-ZeroInflated")
d$verification <- renameAtoB(d$verification, "DESeq2.ZI", "DESeq2-ZeroInflated")
d$evaluation <- renameAtoB(d$evaluation, "GLMM_NB", "GLMM")
d$verification <- renameAtoB(d$verification, "GLMM_NB", "GLMM")
d <- d %>%
  mutate_if(sapply(d, is.character), as.factor)
# d$verification <- renameAtoB(d$verification, "GLMM", "GLMM-ZINB")
# d$evaluation <- renameAtoB(d$evaluation, "GLMM", "GLMM-ZINB")

@ 

<<sensitivityGrid, dev="pdf", fig.width=8, fig.height=6, fig.cap="Sensitivity, where each algorithm's calls (adjusted $p$-value $< .1$) in the evaluation set (color boxes) is compared against itselfs (adjusted $p$-value $< .1$) in the verification set (grey labels).">>=
# d.glmm <- d.glmm[complete.cases(d.glmm),]
# png("/blackhole/alessia/CircModel/power/Figure/Power_sensitivity_ALZ.png", res = 200, units = "cm", width = 25, height = 15)
p <- ggplot(d, aes(x=evaluation,y=sensitivity,color=evaluation))
p + geom_boxplot(outlier.colour=rgb(0,0,0,0)) + theme_bw() + 
  # facet_wrap(~ detection.method) + 
  geom_point(position = position_jitter(w = 0.1, h = 0), color="grey50", size=1) +
  scale_color_manual(values=cols) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 15),
        axis.text.y = element_text(size = 15),
        axis.title=element_text(size=15,face="bold"),
          # axis.text.y.left = element_text(size = 11),
          strip.text.x = element_text(size = 13)) + 
  ggtitle("IPF - Dataset") +
  xlab("")
# dev.off()
@

<<precisionGrid, dev="pdf", fig.width=8, fig.height=6, fig.cap="Precision, where each algorithm's calls (adjusted $p$-value $< .1$) in the evaluation set (color boxes) is compared against itselfs (adjusted $p$-value $< .1$) in the verification set (grey labels).">>=
# png("/blackhole/alessia/CircModel/power/Figure/Power_precision_ALZ.png", res = 200, units = "cm", width = 25, height = 15)
p <- ggplot(d, aes(x=evaluation,y=precision,color=evaluation))
p + geom_boxplot(outlier.colour=rgb(0,0,0,0)) + theme_bw() + 
  # facet_wrap(~ detection.method) + 
  scale_color_manual(values = cols) + 
  geom_point(position = position_jitter(w = 0.1, h = 0), color="grey50", size=1) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 15),
        axis.text.y = element_text(size = 15),
        axis.title=element_text(size=14,face="bold"),
          # axis.text.y.left = element_text(size = 11),
          strip.text.x = element_text(size = 13)) + 
  ggtitle("IPF - Dataset") +
  xlab("")
# dev.off()
@

\clearpage

\section{Area Under Precision Recall Curve (AUPRC)}

<<Recallcurve, echo = FALSE , warning = FALSE, message = FALSE, error = FALSE>>=
library(PRROC)
precall = function(algo, rep, gold = "GLMM_NB") {
  # rep = 1
  # recall = pr.curve(resTes[[rep]][[algo]][resHeldout[[rep]][[gold]] < alphaOut],
  #                   resTes[[rep]][[algo]][!resHeldout[[rep]][[gold]] < alphaOut], curve = TRUE)$curve[, 1]
  # precision = pr.curve(resTes[[rep]][[algo]][resHeldout[[rep]][[gold]] < alphaOut],
  #                      resTes[[rep]][[algo]][!resHeldout[[rep]][[gold]] < alphaOut], curve = TRUE)$curve[, 2]
  auc = pROC::roc(as.numeric(resHeldout[[rep]][[gold]] < alphaOut),
                  as.numeric(resTes[[rep]][[algo]] < alphaOut))
  # auc = AUC::roc(1-resTes[[rep]][[algo]],
  #                as.numeric(resHeldout[[rep]][[gold]] < alphaOut))
  fg <- 1-resTes[[rep]][[algo]][resHeldout[[rep]][[gold]] <= alphaOut]
  bg <- 1-resTes[[rep]][[algo]][resHeldout[[rep]][[gold]] > alphaOut]
  pr <- try(pr.curve(scores.class0 = fg, scores.class1 = bg, curve = T))
  # plot(pr)
  aupr = data_frame(#recall = pr$curve[,1],
                    #precision = pr$curve[,2],
                    AUC = auc$auc,
                    AUPRC = ifelse(class(pr)[1] == "try-error", NA, pr$auc.integral),
                    B = rep,
                    model = algo)
  return(aupr)
  }

res_accuracy = list()
for(algo in names(resTes[[1]])){
  res = rbindlist(lapply(1:nreps, function(x) precall(algo = algo, rep = x, gold = "GLMM_NB")))
  res_accuracy[[algo]] = res
}
AUPRC = rbindlist(res_accuracy, use.names = T)
AUPRC$model = factor(AUPRC$model)
AUPRC$model <- renameAtoB(AUPRC$model, "edgeR.robust", "edgeR-robust")
AUPRC$model <- renameAtoB(AUPRC$model, "edgeR.ZINBWave", "edgeR-ZINB Wave")
AUPRC$model<- renameAtoB(AUPRC$model, "DESeq2.ZINBWave", "DESeq2-ZINB Wave")
AUPRC$model <- renameAtoB(AUPRC$model, "DESeq2.glmGamPoi", "DESeq2-GamPoi")
AUPRC$model<- renameAtoB(AUPRC$model, "DESeq2.ZI", "DESeq2-ZeroInflated")
AUPRC$model = renameAtoB(AUPRC$model, "GLMM_NB", "GLMM")
p <- ggplot(AUPRC, aes(x = reorder(model, AUPRC), y = AUPRC, color = model))
p + geom_boxplot(outlier.colour=rgb(0,0,0,0)) + theme_bw() + 
  # facet_wrap(~ detection.method) + 
  scale_color_manual(values = cols) + 
  geom_point(position = position_jitter(w = 0.1, h = 0), color="grey50", size=1) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 15),
        axis.text.y = element_text(size = 15),
        axis.title=element_text(size=14,face="bold"),
          # axis.text.y.left = element_text(size = 11),
          strip.text.x = element_text(size = 13)) + 
  xlab("")

@

\section{Clustering of calls}

<<clustSetup>>=
alpha <- .1
library("abind")
library("ggplot2")
library("ggdendro")
library("cowplot")
library("gridExtra")
library("grid")
methods <- c("DESeq2",
             "DESeq2.ZI",
             "DESeq2.glmGamPoi",
             "DESeq2.ZINBWave",
             "edgeR",
             "edgeR.robust",
             "edgeR.ZINBWave",
             "circMeta",
             "voom",
             "GLMM_NB")

names(cols) <- methods
# first with evaluation sets
nreps = 30
j0 <- lapply(1:nreps, function(i) {
  # i=1
  #print(i)
  dt <- resTes[[i]]
  colnames(dt) <- c(colnames(dt)[c(1:7)], "voom", "circMeta", 
                    "GLMM")
  m <- as.matrix(dist(t(dt) <= alpha), method="binary")
  return(m)
})

j <- abind(j0,along=3)
average.Jaccard <- apply(j,c(1,2),mean)
average.Jaccard <- as.dist(average.Jaccard)
hcTest <- hclust(average.Jaccard)


# again with verification sets
j0 <- lapply(1:nreps, function(i) {
  dt <- resHeldout[[i]]
  colnames(dt) <- c(colnames(dt)[c(1:7)], "voom", "circMeta", 
                    "GLMM")
  m <- as.matrix(dist(t(dt) <= alpha), method="binary")
  return(m)
})
j <- abind(j0,along=3)
average.Jaccard <- apply(j,c(1,2),mean)
average.Jaccard <- as.dist(average.Jaccard)
hcHeldout <- hclust(average.Jaccard)

@

<<clustMethods, dev="pdf", fig.align="center", fig.width=10, fig.height=12, fig.cap="Clustering of calls (adjusted $p$-value $< .1$) with distances based on the Jaccard index">>=

g_horizontal_dendrogram_Heldout <- ggplot() + 
    geom_segment(data=dendro_data(hcHeldout)$segments, aes(x=x, y=y, xend=xend, yend=yend)) + 
    geom_label(data=dendro_data(hcHeldout)$labels, aes(x=x, y=y, label=label, 
                                                         hjust=-0.05,color=label), nudge_y = 0) +
    coord_flip() + scale_y_reverse(expand = c(0,0,0,0)) + scale_x_reverse() +
    scale_color_manual(values = cols) +
    theme(axis.line.y=element_blank(),
          axis.ticks.y=element_blank(),
          axis.line.x=element_blank(),
          axis.ticks.x=element_blank(),
          axis.text.y=element_blank(),
          axis.title.y=element_blank(),
          axis.text.x=element_blank(),
          axis.title.x=element_blank(),
          panel.background=element_rect(fill="white"),
          panel.grid=element_blank(),
          legend.position = "none",
          panel.spacing = unit(0, "lines"),
          plot.margin = unit(c(0.5,0.5,0.5, 0.5), "cm")) + 
  expand_limits(y = -round(max(segment(dendro_data(hcHeldout))$y) * 0.5, 1))


get_legend_dendo <- get_legend(ggplot() + 
    geom_segment(data=dendro_data(hcHeldout)$segments, aes(x=x, y=y, xend=xend, yend=yend)) + 
    geom_point(data=dendro_data(hcHeldout)$labels, aes(x=x, y=y,color=factor(label, levels = names(cols), ordered = T)),size = 5) +
    scale_y_continuous() +
    #scale_y_reverse(expand=c(2,1)) + scale_x_reverse(expand=c(2,1)) +
    scale_color_manual(values = cols) +
    theme(axis.line.y=element_blank(),
          axis.ticks.y=element_blank(),
          axis.line.x=element_blank(),
          axis.ticks.x=element_blank(),
          axis.text.y=element_blank(),
          axis.title.y=element_blank(),
          axis.text.x=element_blank(),
          axis.title.x=element_blank(),
          panel.background=element_rect(fill="white"),
          panel.grid=element_blank(),
          legend.position = "bottom",
          panel.spacing = unit(0, "lines"),
          plot.margin = unit(c(0.5,0.5,0.5, 0.5), "cm")) +
      guides(color = guide_legend(title = "Methods:",title.position = "left",nrow = 2)))

# now add the title
title <- ggdraw() +
  draw_label(
    "Clustering of calls in Verification set",
    fontface = 'bold',
    x = 0,
    hjust = 0, size = 12
  ) +
  theme(
    # add margin on the left of the drawing canvas,
    # so title is aligned with left edge of first plot
    plot.margin = margin(0, 0, 0, 7)
  )

g_horizontal_dendrogram_Test <- ggplot() + 
    geom_segment(data=dendro_data(hcTest)$segments, aes(x=x, y=y, xend=xend, yend=yend)) + 
    geom_label(data=dendro_data(hcTest)$labels, aes(x=x, y=y, label=label, hjust=-0.05,color=label), nudge_y = 0) +
    coord_flip() + scale_y_reverse(expand = c(0,0,0,0)) + scale_x_reverse() +
    scale_color_manual(values = cols) +
    theme(axis.line.y=element_blank(),
          axis.ticks.y=element_blank(),
          axis.line.x=element_blank(),
          axis.ticks.x=element_blank(),
          axis.text.y=element_blank(),
          axis.title.y=element_blank(),
          axis.text.x=element_blank(),
          axis.title.x=element_blank(),
          panel.background=element_rect(fill="white"),
          panel.grid=element_blank(),
          legend.position = "none",
          panel.spacing = unit(0, "lines"),
          plot.margin = unit(c(0.5,0.5,0.5, 0.5), "cm")) + 
  expand_limits(y = -round(max(segment(dendro_data(hcTest))$y) * 0.5, 1))


# now add the title
titleTest <- ggdraw() +
  draw_label(
    "Clustering of calls in Evaluation set",
    fontface = 'bold',
    x = 0,
    hjust = 0, size = 12
  ) +
  theme(
    # add margin on the left of the drawing canvas,
    # so title is aligned with left edge of first plot
    plot.margin = margin(0, 0, 0, 7)
  )

Heldplot <- plot_grid(title, g_horizontal_dendrogram_Heldout,
                    # plot_grid(plotlist = g_horizontal_dendrogram_Heldout, 
                    #          ncol = 2, #align = 'vh',
                    #          hjust = c(-0.1, 0.8, -0.1, 0.8, -0.1, 0.8, -0.1), 
                    #          vjust = -1.35,
                    #          labels = names(heldMat), 
                    #          label_size = 9), 
                    ncol = 1, rel_heights = c(0.1, 1))
Testplot <- plot_grid(titleTest, g_horizontal_dendrogram_Test,
                    # plot_grid(plotlist = g_horizontal_dendrogram_Test, 
                    #          ncol = 2, #align = 'vh',
                    #          hjust = c(-0.1, 0.8, -0.1, 0.8, -0.1, 0.8, -0.1), 
                    #          vjust = -1.35,
                    #          labels = names(testMat),
                    #          label_size = 9
                    #          ), 
                    ncol = 1, rel_heights = c(0.1, 1))
# png("/blackhole/alessia/CircModel/robustness/ALZ_Clusteringofcalls.png", res = 200, units = "cm", width = 30, height = 45)
grid.arrange(Heldplot, Testplot, get_legend_dendo, ncol=2, nrow=2, widths=c(2.3, 2.3), heights=c(1, 0.1))
# dev.off()
@

\clearpage

\section{Session information}

<<sessInfo, echo=FALSE, results="asis">>=
toLatex(sessionInfo())
@ 


\end{document}
